export enum NotificationType {
  MEDICINE_REMINDER_BEFORE = 'MEDICINE_REMINDER_BEFORE',
  MEDICINE_REMINDER_TIME = 'MEDICINE_REMINDER_TIME',
  MEDICINE_SKIP_ALERT = 'MEDICINE_SKIP_ALERT',
  STOCK_ALERT = 'STOCK_ALERT',
  AI_WARNING = 'AI_WARNING',
  TRAVEL_REMINDER_H1 = 'TRAVEL_REMINDER_H1',
}
